# Generated by Django 6.1 on 2026-08-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('revendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_origem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Origem')),
                ('moeda_origem', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda de Origem')),
                ('valor_destino', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Destino')),
                ('moeda_destino', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda de Destino')),
                ('taxa_cambio', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Taxa de Câmbio')),
                ('data_conversao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Conversão')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revendedores.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Conversão',
                'verbose_name_plural': 'Conversões',
                'ordering': ['-data_conversao'],
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('MPESA', 'M-Pesa'), ('EMOLA', 'E-Mola'), ('MKASH', 'mKash'), ('VISA', 'Visa')], max_length=20, verbose_name='Método de Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Depositado')),
                ('moeda', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda')),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência Externa')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('falhou', 'Falhou')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_deposito', models.DateTimeField(auto_now_add=True, verbose_name='Data do Depósito')),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Confirmação')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revendedores.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
                'ordering': ['-data_deposito'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revendedores.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='TaxaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_origem', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda de Origem')),
                ('moeda_destino', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda de Destino')),
                ('taxa_compra', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Taxa de Compra')),
                ('taxa_venda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Taxa de Venda')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('fonte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Taxa de Câmbio',
                'verbose_name_plural': 'Taxas de Câmbio',
                'ordering': ['-data_atualizacao'],
                'unique_together': {('moeda_origem', 'moeda_destino')},
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('conversao', 'Conversão'), ('compra', 'Compra'), ('estorno', 'Estorno')], max_length=20, verbose_name='Tipo de Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('moeda', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], max_length=3, verbose_name='Moeda')),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Anterior')),
                ('saldo_novo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Novo')),
                ('referencia_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Referência')),
                ('data_transacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revendedores.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-data_transacao'],
            },
        ),
    ]
