# Generated by Django 6.1 on 2026-08-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_mzn',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco_usd',
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='% de comissão para o revendedor', max_digits=5),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_zar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock_atual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
