# Generated by Django 6.1 on 2026-08-14 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Anúncio')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link de Destino')),
                ('posicao', models.CharField(choices=[('hero', 'Hero Banner (Topo)'), ('sidebar', 'Barra Lateral'), ('produtos', 'Entre Produtos'), ('rodape', 'Rodapé'), ('popup', 'Popup')], default='hero', max_length=20, verbose_name='Posição')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['posicao', 'ordem'],
            },
        ),
    ]
