# Generated by Django 6.0.6 on 2026-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_devedor',
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_devedor_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Devedor (MZN)'),
        ),
    ]
