# Generated by Django 6.0.6 on 2026-08-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_saldo_devedor_and_more'),
        ('encomendas', '0002_remove_encomenda_comissao_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (MZN)')),
                ('metodo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência Bancária'), ('mpesa', 'M-Pesa'), ('emola', 'E-Mola'), ('mkash', 'mKash'), ('outro', 'Outro')], default='dinheiro', max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='clientes.cliente')),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='encomendas.encomenda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
