# Generated by Django 6.1 on 2026-08-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0001_initial'),
        ('produtos', '0001_initial'),
        ('revendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número do Pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('moeda', models.CharField(choices=[('MZN', 'Metical'), ('USD', 'Dólar Americano'), ('ZAR', 'Rand Sul-Africano')], default='USD', max_length=3, verbose_name='Moeda')),
                ('status', models.CharField(choices=[('aguardando_separacao', 'Aguardando Separação'), ('em_separacao', 'Em Separação'), ('embalado', 'Embalado'), ('em_transporte', 'Em Trânsito'), ('chegou_loja', 'Chegou à Loja'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_separacao', max_length=30, verbose_name='Status')),
                ('data_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('data_separacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Separação')),
                ('data_embalagem', models.DateTimeField(blank=True, null=True, verbose_name='Data de Embalagem')),
                ('data_transporte', models.DateTimeField(blank=True, null=True, verbose_name='Data de Transporte')),
                ('data_chegada_loja', models.DateTimeField(blank=True, null=True, verbose_name='Data de Chegada à Loja')),
                ('data_levantamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Levantamento')),
                ('funcionario_entrega', models.CharField(blank=True, max_length=100, null=True, verbose_name='Funcionário que Entregou')),
                ('loja_recolha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojas.loja', verbose_name='Loja de Recolha')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revendedores.revendedor', verbose_name='Revendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
    ]
