# Generated by Django 6.0.6 on 2026-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='comissao_total',
        ),
        migrations.RemoveField(
            model_name='encomenda',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='itemencomenda',
            name='comissao_item',
        ),
        migrations.RemoveField(
            model_name='itemencomenda',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='itemencomenda',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='comissao_total_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão Total (MZN)'),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='valor_total_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total (MZN)'),
        ),
        migrations.AddField(
            model_name='itemencomenda',
            name='comissao_item_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comissão Item (MZN)'),
        ),
        migrations.AddField(
            model_name='itemencomenda',
            name='preco_unitario_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário (MZN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemencomenda',
            name='subtotal_mzn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (MZN)'),
            preserve_default=False,
        ),
    ]
