# Generated by Django 6.1 on 2026-08-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Produto')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço em USD')),
                ('preco_mzn', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço em MZN')),
                ('preco_zar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço em ZAR (Rand)')),
                ('stock_atual', models.IntegerField(default=0, verbose_name='Stock Atual')),
                ('stock_minimo', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL da Imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
