# Generated by Django 6.0.6 on 2026-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_zar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=20.0, help_text='% de comissão para o revendedor', max_digits=5)),
                ('stock_atual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('is_active', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
