# Generated by Django 6.0.6 on 2026-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_zar',
        ),
        migrations.AddField(
            model_name='produto',
            name='comissao_mzn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comissão (MZN)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_mzn',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço (MZN)'),
        ),
    ]
