# Generated by Django 6.0.6 on 2026-08-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=20, unique=True, verbose_name='Código Único')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('documento_tipo', models.CharField(choices=[('BI', 'Bilhete de Identidade'), ('PASSAPORTE', 'Passaporte'), ('DIRE', 'DIRE')], max_length=20, verbose_name='Tipo de Documento')),
                ('documento_numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Documento')),
                ('documento_upload', models.CharField(blank=True, max_length=255, null=True, verbose_name='Upload do Documento')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Província')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('loja_recolha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Loja de Recolha')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('data_ultimo_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Login')),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
                'ordering': ['nome_completo'],
            },
        ),
    ]
